'use client';

import React, { useState, useEffect } from 'react';
import { useParams } from 'next/navigation';
import axios from 'axios';
import { CheckIcon, XMarkIcon, ExclamationTriangleIcon } from '@heroicons/react/24/outline';

const API_BASE = 'http://localhost:5000/api/v1';

export default function PublicOnboardingPage() {
  const params = useParams();
  const token = params.token as string;

  const [profile, setProfile] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [statusMsg, setStatusMsg] = useState<{ type: 'success' | 'error'; text: string } | null>(null);
  
  // Rejection modal
  const [showRejectModal, setShowRejectModal] = useState(false);
  const [rejectReason, setRejectReason] = useState('');
  const [submitting, setSubmitting] = useState(false);

  useEffect(() => {
    if (token) {
      fetchProfile();
    }
  }, [token]);

  const fetchProfile = async () => {
    try {
      setLoading(true);
      setError(null);
      const res = await axios.get(`${API_BASE}/public-onboarding/${token}`);
      if (res.data?.success) {
        setProfile(res.data.data);
      } else {
        setError(res.data?.error?.message || 'Failed to load onboarding profile.');
      }
    } catch (err: any) {
      console.error(err);
      setError(err.response?.data?.error?.message || 'Invalid or expired onboarding link.');
    } finally {
      setLoading(false);
    }
  };

  const handleApprove = async () => {
    try {
      setSubmitting(true);
      setStatusMsg(null);
      const res = await axios.post(`${API_BASE}/public-onboarding/${token}/approve`);
      if (res.data?.success) {
        setStatusMsg({ type: 'success', text: 'You have successfully approved your profile! Thank you.' });
        fetchProfile();
      }
    } catch (err: any) {
      setStatusMsg({ type: 'error', text: err.response?.data?.error?.message || 'Failed to submit approval.' });
    } finally {
      setSubmitting(false);
    }
  };

  const handleRejectSubmit = async () => {
    if (!rejectReason.trim()) {
      alert('Please enter a reason for requesting revisions.');
      return;
    }
    try {
      setSubmitting(true);
      setStatusMsg(null);
      const res = await axios.post(`${API_BASE}/public-onboarding/${token}/request-changes`, {
        reason: rejectReason.trim()
      });
      if (res.data?.success) {
        setStatusMsg({ type: 'success', text: 'Revisions requested successfully. The matching agent will review your feedback.' });
        setShowRejectModal(false);
        setRejectReason('');
        fetchProfile();
      }
    } catch (err: any) {
      setStatusMsg({ type: 'error', text: err.response?.data?.error?.message || 'Failed to submit request.' });
    } finally {
      setSubmitting(false);
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-slate-900 text-white flex flex-col justify-center items-center">
        <div className="animate-spin h-10 w-10 border-4 border-indigo-500 border-t-transparent rounded-full mb-4"></div>
        <p className="text-sm text-slate-400">Loading your profile review details...</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen bg-slate-900 text-white flex flex-col justify-center items-center px-4">
        <div className="bg-slate-800 p-8 rounded-2xl shadow-xl max-w-md w-full border border-slate-700 text-center">
          <ExclamationTriangleIcon className="h-16 w-16 mx-auto mb-4 text-red-500" />
          <h1 className="text-xl font-bold mb-2">Review Link Expired</h1>
          <p className="text-sm text-slate-400 mb-6">{error}</p>
          <p className="text-xs text-slate-500">Please contact your relationship manager to request a new link.</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="text-center mb-10">
          <span className="text-xs font-bold uppercase tracking-widest text-indigo-400 bg-indigo-950/50 px-3 py-1 rounded-full border border-indigo-850">
            MatriMitra Profile Verification
          </span>
          <h1 className="text-3xl font-extrabold text-white mt-3 tracking-tight">Review Your Profile Details</h1>
          <p className="text-sm text-slate-400 mt-2 max-w-xl mx-auto">
            Please carefully review the details generated by your matchmaking agent. Click Approve to confirm or request changes if you spot errors.
          </p>
        </div>

        {statusMsg && (
          <div className={`mb-8 p-4 rounded-xl border ${
            statusMsg.type === 'success' ? 'bg-emerald-950/40 border-emerald-850 text-emerald-300' : 'bg-red-950/40 border-red-850 text-red-300'
          }`}>
            <p className="text-sm font-semibold text-center">{statusMsg.text}</p>
          </div>
        )}

        {/* Info Box */}
        {profile?.clientApproved && (
          <div className="mb-8 p-4 bg-emerald-950/30 border border-emerald-900/50 rounded-xl flex items-center gap-3 text-emerald-400">
            <CheckIcon className="h-5 w-5 shrink-0" />
            <span className="text-sm font-medium">You have approved this profile. Status: <strong className="text-emerald-300 uppercase">{profile.status}</strong></span>
          </div>
        )}

        {profile?.clientRejectedReason && !profile?.clientApproved && (
          <div className="mb-8 p-4 bg-amber-950/30 border border-amber-900/50 rounded-xl">
            <span className="text-sm font-semibold text-amber-400 block mb-1">Your requested revisions:</span>
            <p className="text-xs text-amber-300 italic">"{profile.clientRejectedReason}"</p>
          </div>
        )}

        {/* Profile Details Grid */}
        <div className="bg-slate-900/50 backdrop-blur-md rounded-3xl border border-slate-800 shadow-xl overflow-hidden p-6 sm:p-8 space-y-8 mb-8">
          
          {/* Section: Basic Info */}
          <div>
            <h2 className="text-lg font-bold text-white mb-4 border-b border-slate-800 pb-2">Personal Information</h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 text-sm">
              <div>
                <span className="text-slate-400 block text-xs">Full Name</span>
                <span className="text-white font-medium">{profile.person?.firstName} {profile.person?.lastName || ''}</span>
              </div>
              <div>
                <span className="text-slate-400 block text-xs">Gender</span>
                <span className="text-white font-medium capitalize">{profile.person?.gender || 'N/A'}</span>
              </div>
              <div>
                <span className="text-slate-400 block text-xs">Relationship to Client</span>
                <span className="text-white font-medium">{profile.relationshipToClient || 'Self'}</span>
              </div>
              <div>
                <span className="text-slate-400 block text-xs">Profile Type</span>
                <span className="text-white font-medium">{profile.profileType}</span>
              </div>
              <div>
                <span className="text-slate-400 block text-xs">Religion / Caste</span>
                <span className="text-white font-medium">
                  {profile.personal?.religion || 'N/A'} {profile.personal?.caste ? `- ${profile.personal.caste}` : ''}
                </span>
              </div>
              <div>
                <span className="text-slate-400 block text-xs">Mother Tongue</span>
                <span className="text-white font-medium">{profile.personal?.motherTongue || 'N/A'}</span>
              </div>
              <div>
                <span className="text-slate-400 block text-xs">Marital Status</span>
                <span className="text-white font-medium">{profile.personal?.maritalStatus || 'N/A'}</span>
              </div>
              <div>
                <span className="text-slate-400 block text-xs">Height / Weight</span>
                <span className="text-white font-medium">
                  {profile.personal?.heightCm ? `${profile.personal.heightCm} cm` : 'N/A'} 
                  {profile.personal?.weightKg ? ` / ${profile.personal.weightKg} kg` : ''}
                </span>
              </div>
              <div>
                <span className="text-slate-400 block text-xs">Current Location</span>
                <span className="text-white font-medium">
                  {profile.personal?.city || 'N/A'}{profile.personal?.state ? `, ${profile.personal.state}` : ''}
                </span>
              </div>
            </div>
          </div>

          {/* Section: Education & Career */}
          <div>
            <h2 className="text-lg font-bold text-white mb-4 border-b border-slate-800 pb-2">Education & Career</h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-6 text-sm">
              <div>
                <h3 className="font-semibold text-slate-300 text-xs mb-2">Education Details</h3>
                {profile.educations && profile.educations.length > 0 ? (
                  profile.educations.map((edu: any, idx: number) => (
                    <div key={idx} className="bg-slate-800/40 p-3 rounded-lg border border-slate-800 mb-2">
                      <div className="font-medium text-white">{edu.qualification}</div>
                      {edu.specialization && <div className="text-slate-400 text-xs">{edu.specialization}</div>}
                      {edu.institution && <div className="text-slate-500 text-xs">{edu.institution}</div>}
                    </div>
                  ))
                ) : (
                  <span className="text-slate-500 text-xs italic">No education history added.</span>
                )}
              </div>
              <div>
                <h3 className="font-semibold text-slate-300 text-xs mb-2">Career Details</h3>
                {profile.careers && profile.careers.length > 0 ? (
                  profile.careers.map((car: any, idx: number) => (
                    <div key={idx} className="bg-slate-800/40 p-3 rounded-lg border border-slate-800 mb-2">
                      <div className="font-medium text-white">{car.profession || 'N/A'}</div>
                      {(car.employer || car.designation) && (
                        <div className="text-slate-400 text-xs">{car.designation || ''} {car.employer ? `@ ${car.employer}` : ''}</div>
                      )}
                      {car.annualIncome && <div className="text-emerald-400 text-xs">Annual Income: {Number(car.annualIncome).toLocaleString('en-IN', { style: 'currency', currency: 'INR' })}</div>}
                    </div>
                  ))
                ) : (
                  <span className="text-slate-500 text-xs italic">No career history added.</span>
                )}
              </div>
            </div>
          </div>

          {/* Section: Family */}
          <div>
            <h2 className="text-lg font-bold text-white mb-4 border-b border-slate-800 pb-2">Family Details</h2>
            {profile.families && profile.families.length > 0 ? (
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-6 text-sm">
                {profile.families.map((fam: any, idx: number) => (
                  <React.Fragment key={idx}>
                    <div>
                      <span className="text-slate-400 block text-xs">Father's Name & Occupation</span>
                      <span className="text-white font-medium block">{fam.fatherName || 'N/A'}</span>
                      {fam.fatherOccupation && <span className="text-xs text-slate-500">{fam.fatherOccupation}</span>}
                    </div>
                    <div>
                      <span className="text-slate-400 block text-xs">Mother's Name & Occupation</span>
                      <span className="text-white font-medium block">{fam.motherName || 'N/A'}</span>
                      {fam.motherOccupation && <span className="text-xs text-slate-500">{fam.motherOccupation}</span>}
                    </div>
                    <div>
                      <span className="text-slate-400 block text-xs">Family Values / Type</span>
                      <span className="text-white font-medium">{fam.familyValues || 'N/A'} ({fam.familyType || 'N/A'})</span>
                    </div>
                    <div>
                      <span className="text-slate-400 block text-xs">Siblings</span>
                      <span className="text-white font-medium">{fam.siblingsCount !== null ? `${fam.siblingsCount} siblings` : 'N/A'}</span>
                    </div>
                  </React.Fragment>
                ))}
              </div>
            ) : (
              <span className="text-slate-500 text-xs italic">No family details added.</span>
            )}
          </div>

          {/* Section: Lifestyle */}
          <div>
            <h2 className="text-lg font-bold text-white mb-4 border-b border-slate-800 pb-2">Lifestyle</h2>
            {profile.lifestyles && profile.lifestyles.length > 0 ? (
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 text-sm">
                {profile.lifestyles.map((life: any, idx: number) => (
                  <React.Fragment key={idx}>
                    <div>
                      <span className="text-slate-400 block text-xs">Food Habit</span>
                      <span className="text-white font-medium capitalize">{life.foodHabit || 'N/A'}</span>
                    </div>
                    <div>
                      <span className="text-slate-400 block text-xs">Smoking</span>
                      <span className="text-white font-medium">{life.smoking === true ? 'Yes' : life.smoking === false ? 'No' : 'N/A'}</span>
                    </div>
                    <div>
                      <span className="text-slate-400 block text-xs">Drinking</span>
                      <span className="text-white font-medium">{life.drinking === true ? 'Yes' : life.drinking === false ? 'No' : 'N/A'}</span>
                    </div>
                    <div>
                      <span className="text-slate-400 block text-xs">Fitness Level</span>
                      <span className="text-white font-medium">{life.fitnessLevel || 'N/A'}</span>
                    </div>
                  </React.Fragment>
                ))}
              </div>
            ) : (
              <span className="text-slate-500 text-xs italic">No lifestyle details added.</span>
            )}
          </div>

          {/* Section: Photos */}
          <div>
            <h2 className="text-lg font-bold text-white mb-4 border-b border-slate-800 pb-2">Profile Photos</h2>
            {profile.photos && profile.photos.length > 0 ? (
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
                {profile.photos.map((photo: any) => (
                  <div key={photo.id} className="relative aspect-[3/4] bg-slate-800 rounded-xl overflow-hidden border border-slate-700 shadow-sm">
                    <img
                      src={photo.cloudinaryUrl}
                      alt="Candidate Profile"
                      className="object-cover w-full h-full"
                    />
                    {photo.isPrimary && (
                      <span className="absolute bottom-2 left-2 bg-indigo-600 text-white text-[9px] font-bold px-2 py-0.5 rounded shadow">
                        Primary Photo
                      </span>
                    )}
                  </div>
                ))}
              </div>
            ) : (
              <span className="text-slate-500 text-xs italic">No photos added.</span>
            )}
          </div>
        </div>

        {/* Buttons Action bar */}
        {!profile?.clientApproved && (
          <div className="flex justify-end gap-x-4">
            <button
              onClick={() => setShowRejectModal(true)}
              disabled={submitting}
              className="inline-flex items-center gap-x-1.5 rounded-xl border border-slate-700 bg-transparent px-5 py-3 text-sm font-semibold text-slate-300 hover:bg-slate-900 transition disabled:opacity-50"
            >
              <XMarkIcon className="h-4 w-4" />
              Request Corrections
            </button>
            <button
              onClick={handleApprove}
              disabled={submitting}
              className="inline-flex items-center gap-x-1.5 rounded-xl bg-indigo-600 px-6 py-3 text-sm font-semibold text-white hover:bg-indigo-500 transition shadow-lg shadow-indigo-650/20 disabled:opacity-50"
            >
              <CheckIcon className="h-4 w-4" />
              Approve Profile
            </button>
          </div>
        )}
      </div>

      {/* Reject Reason Modal */}
      {showRejectModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950 bg-opacity-70 backdrop-blur-sm">
          <div className="bg-slate-900 border border-slate-800 rounded-2xl max-w-md w-full p-6 shadow-2xl">
            <h3 className="text-lg font-bold text-white mb-2">Request Revisions</h3>
            <p className="text-xs text-slate-400 mb-4">
              Please write a brief note indicating what fields need to be corrected. The agency will be notified immediately.
            </p>

            <textarea
              rows={4}
              value={rejectReason}
              onChange={(e) => setRejectReason(e.target.value)}
              placeholder="Example: My date of birth is incorrect (it should be 1995 instead of 1996), and please update my designation to Senior Engineer..."
              className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3.5 py-2.5 text-xs text-white placeholder-slate-600 focus:outline-none focus:ring-2 focus:ring-indigo-500"
            />

            <div className="flex justify-end gap-x-3 mt-6">
              <button
                type="button"
                onClick={() => {
                  setShowRejectModal(false);
                  setRejectReason('');
                }}
                disabled={submitting}
                className="px-4 py-2 border border-slate-800 rounded-lg text-xs font-semibold text-slate-400 hover:bg-slate-850"
              >
                Cancel
              </button>
              <button
                type="button"
                onClick={handleRejectSubmit}
                disabled={submitting}
                className="px-4 py-2 bg-indigo-650 hover:bg-indigo-600 rounded-lg text-xs font-semibold text-white min-w-[70px] flex items-center justify-center"
              >
                {submitting ? 'Sending...' : 'Submit'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
